### ISSUE TITLE
Add the Firebase login and logout ui

### ISSUE THREAD

**Issue by BentleyDavis** [SettleIt/ReasonRoot#11]
https://github.com/firebase/firebaseui-web

- [x] Popup sign-In for all sign-in providers
- [x] Sign-out Button
- [x] The sign-In and sign-out buttons should be in both the widget settings section and as a visible button on the edit page.

**Comment by EdgarOPG** [comment]
Even sign in with cellphone number provider?

**Comment by BentleyDavis** [comment]
Don't actually set up and providers except google yet. Put the code in so that they will work when they are set up. Hopefully we can just comment out any providers we are not using so they do not show up. If that can not be done simply then implement the code and let me know and I can have a look. Let's not make any real changes to their code. I just want to plug it in and use it as is.
