### ISSUE TITLE
Should not use the js folder

### ISSUE THREAD

**Issue by BentleyDavis** [SettleIt/ReasonRoot#25]
The `js` folder was used for typescript compiling when not using webpack.
In index.js there is the below line referencing the `rrDisplay` file from the `js` folder.
```
import RRDisplay from './js/src/rrDisplay.js';
```
the `rrDisplay` object should be built by webpack into `bundle.js` without this reference.

**Comment by EdgarOPG** [comment]
I see, I will change JavaScript libs to the TypeScript ones and correct this behavior on index.js

**Comment by EdgarOPG** [comment]
I find another bug, but it's easy to fix, I forgot to import the class Claim on the file, in the line 8 lack `import Claim from './Claim.js';`

**Comment by BentleyDavis** [comment]
There is still a js folder and files under it. Why are they there or should they be removed.

**Comment by EdgarOPG** [comment]
No, the js folder is unused, it was erased.

**Comment by BentleyDavis** [comment]
For some reason there were still JS files in the dev branch even though I approved all your items on this card. I removed them and committed the code. You might want to merge dev into your other branches again just to make sure you are in sync.
