### ISSUE TITLE
Edit webpage

### ISSUE THREAD

**Issue by BentleyDavis** [SettleIt/ReasonRoot#38]
Create a web page that display all the editing tools and parts so people can view, edit and create new claims.

- [x] Create widget.html and move the claims from SettleIt.org to this page so we can ensure they continue to work.
- [x] Create edit.html and move the "create new claim" button to this web page.
- [x] Change index.html to just have links (as `a` tag) to edit.html and widget.html
the rest of the items are for edit.html only
- [x] If the url has no parameters but a person is logged in it will list their claims that have made so far.
- [x] if the URL has `?id=` and an id in it then the page will bring up that claim.
- [x] If they click the "new Claim" button it will create a new claim and change the URL to match.

**Comment by BentleyDavis** [comment]
I can not see " If the url has no parameters but a person is logged in it will list their claims that have made so far." Since if you refresh the page the system does not detect if you are logged in. Did we get this working. If not, it is ok. We can move it out to a separate card. If you got it working please let me know the steps to show it works.

**Comment by EdgarOPG** [comment]
yeah you're right, if the page is reloaded after set login the app doesn't "know" that the user has signed before. It can be moved to another card?

**Comment by EdgarOPG** [comment]
Another thing I did not think about is that there are no alerts, for example if you are not logged in, you can not create new RRs.
