### ISSUE TITLE
Sign-In Improvements

### ISSUE THREAD

**Issue by BentleyDavis** [SettleIt/ReasonRoot#47]
Create a sign-in component (for use on the edit page for now and in the settings of the ReasonRoot in the future)
- [x] The Sign in button should only be present if the user is signed out
- [x] The sign out button should only be visible if the user is signed in
- [x] If the user is signed in it should say "Hello username" (where the sign in button was)
- [x] If the user refreshes the page they should remain signed in.

**Comment by EdgarOPG** [comment]
Are you talking about both pairs of buttons?
Where should the message "Hello username" be displayed?
When I upload the page I keep my firebase session, I guess it is another error.

**Comment by BentleyDavis** [comment]
Ideally both pairs of buttons should use the same code but we can start with the buttons on the edit page. The "Hello" should be where the sign in button would be. It can be one if statement.

**Comment by EdgarOPG** [comment]
Hello, you could check the last commit I made before doing a PR, to see if you still have the problem that when refreshing the page you lose the session and check the other points of the task 47, I made some changes within the settings menu Of each RR, of course they are only suggestions for the user experience, you could also tell me that you seem to fit them.

**Comment by BentleyDavis** [comment]
It stays logged it now. Looks better.
